
name: flutter_nexus_hub
description: A comprehensive Flutter mobile application showcasing various Android features
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path: ^1.8.3
  flutter_local_notifications: ^14.1.1
  timezone: ^0.9.2
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  maps_launcher: ^2.2.0
  http: ^0.13.6
  xml: ^6.3.0
  url_launcher: ^6.1.11
  flutter_email_sender: ^6.0.1
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
